### ISSUE TITLE
Error, unfinished transaction scenarios 

### ISSUE THREAD

**Issue by adamovivan** [adamovivan/SEP#8]
"Rešavanje svih mogućih error i unfinished transaction scenarija, poput onog gde kupac zatvara tab neposredno pre nego što će platiti, gde izvrši plaćanje na eksternom servisu, ali dođe do greške u KPu pa NC ne dobije informaciju da je čovek platio i sl. Akcenat ovog segmenta je da se dobro razmotre sve moguće situacije otkaza i da KP podrži strategiju za rešavanje potencijalnog problema."

**Comment by DejanPredojevic** [comment]
dodati za paypal
